In [1]:
import numpy as np
import pandas as pd

### Question 1

In [2]:
pd.__version__

'2.0.3'

This can be done by `pd.read_csv` in fact!

In [3]:
df_ = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv')

### Question 2

In [5]:
df_.shape

(20640, 10)

10 Columns

### Question 3 

In [6]:
df_.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

Total bedrooms has missing values

### Question 4

In [8]:
df_.ocean_proximity.nunique()

5

Five unique columns

### Question 6

In [9]:
df_.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [11]:
(df_
 .query("ocean_proximity=='NEAR BAY'")
 .median_house_value.mean()
)

259212.31179039303

259212 is the correct answer

In [16]:
bedrooms_mean = (df_
 .total_bedrooms.mean()
)
bedrooms_mean

537.8705525375618

In [15]:
(df_
 .assign(total_bedrooms = lambda df_: df_.total_bedrooms.fillna(bedrooms_mean))
 .total_bedrooms.mean()
)

537.8705525375617

No, the value hasn't changed

### Question 7 

In [23]:
X = (df_
 .query("ocean_proximity=='ISLAND'")
 .loc[:, ['housing_median_age', 'total_rooms', 'total_bedrooms']]
 .to_numpy()
)
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

Matrix-Matrix multiplication between the X.T and X

In [28]:
XTX = X.T.dot(X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

Inverse of XTX:

In [29]:
inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

Multiply the inverse of $XTX$ with the transpose of $X$, and then multiply the result by $y$. Call the result $w$.

In [33]:
y = np.array([950, 1300, 800, 1000, 1300])

In [34]:
w = (inv_XTX
     .dot(X.T)
     .dot(y)
    )

In [35]:
w

array([23.12330961, -1.48124183,  5.69922946])

Last values is 5.6992