In [1]:
import numpy as np

In [3]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])

# addition 
u + v

array([ 5, 11, 13, 12])

In [4]:
# subtraction 
u - v

array([-1,  3, -3,  0])

In [5]:
# scalar multiplication 
2 * v

array([ 6,  8, 16, 12])

In [6]:
u * v

array([ 6, 28, 40, 36])

### Dot product

When you're dealing with a row vector $ \mathbf{A} $ and a column vector $\mathbf{B}$, the dot product can also be represented using matrix multiplication. In this context, $\mathbf{A}$ is often written with a transpose superscript to indicate that it's a row vector:

$$
\mathbf{A}^\top \mathbf{B} = a_1 \cdot b_1 + a_2 \cdot b_2 + \ldots + a_n \cdot b_n = \sum_{i=1}^{n} a_i \cdot b_i
$$

The superscript $\top$ indicates the transpose of $\mathbf{A}$, emphasizing that you're performing a row-by-column multiplication.

In [23]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

In [24]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result += (u[i] * v[i])
    
    return result

In [25]:
vector_vector_multiplication(u, v)

14.0

In [27]:
u.dot(v)

14

### Matrix-Vector Multiplication

Matrix multiplication involves summing up the products of the respective elements in the rows of the first matrix and the columns of the second matrix. Let $ \mathbf{A} $ be an $ m \times n $ matrix and $ \mathbf{B} $ be an $ n \times p $ matrix. The resulting $ m \times p $ matrix $ \mathbf{C} $ is given by:

$$
\mathbf{C}_{ij} = \sum_{k=1}^{n} \mathbf{A}_{ik} \cdot \mathbf{B}_{kj}
$$

Here, $ \mathbf{C}_{ij} $ is the element in the $ i^{th} $ row and $ j^{th} $ column of $ \mathbf{C} $. $ \mathbf{A}_{ik} $ is the element in the $ i^{th} $ row and $ k^{th} $ column of $ \mathbf{A} $, and $ \mathbf{B}_{kj} $ is the element in the $ k^{th} $ row and $ j^{th} $ column of $ \mathbf{B} $.

The sum runs over $ k $, ranging from 1 to $ n $, which is the common dimension between $ \mathbf{A} $ and $ \mathbf{B} $.

In [28]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [29]:
U.shape

(3, 4)

In [30]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [31]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [32]:
U.dot(v)

array([14,  5,  5])

### Matrix-Matrix multiplication

Canbe though of as multiple Matrix-Vector multiplications.

$$
\mathbf{C}_{ij} = \sum_{k=1}^{n} \mathbf{A}_{ik} \cdot \mathbf{B}_{kj}
$$

In [42]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [36]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [37]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

### Identity Matrix)

In [39]:
I = np.eye(3)

In [41]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [40]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

Is useful for explaining matrix inverse.

NOTE: **Only square matrices have inverse!**

In [45]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [47]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [48]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Inversion will be useful for linear regression.